import {attribute, rangeKey, table, autoGeneratedHashKey,hashKey} from '@aws/dynamodb-data-mapper-annotations'
import {embed} from '@aws/dynamodb-data-mapper'

//
// In this example your GSI is called `ItemIdIndex`
//
@table('items')
class Item {
  @hashKey() // <-- this is your normal hash key (not part of GSI)
  itemId: string;

  @rangeKey({ // <-- this is your normal range key (not part of GSI)
    // BUT, this also acts as the HashKey for your GSI
    indexKeyConfigurations: {
      ItemIdIndex: 'HASH'
    }
  })
  displayName: string;

  @attribute({
    // And this other attribute acts as the GSI's RangeKey
    indexKeyConfigurations: {
      ItemIdIndex: 'RANGE'
    }
  })
  foo: string;

  @attribute()
  bar: string;
}