/** @format */

import {attribute, rangeKey, table, autoGeneratedHashKey} from '@aws/dynamodb-data-mapper-annotations'
import {embed} from '@aws/dynamodb-data-mapper'
import {RuleSet} from './ruleSet'
import uuidV4 = require('uuid/v4')

@table('userTable')
export class User {
  @autoGeneratedHashKey()
  uuid: string

  @rangeKey()
  username: string

  @attribute({defaultProvider: () => new Date()})
  createdAt?: Date

  @attribute()
  name?: string

  @attribute()
  age?: number

  @attribute()
  passwordHash?: string

  @attribute()
  passwordSalt?: string

  @attribute({memberType: embed(RuleSet)})
  ruleSet?: Array<RuleSet>
}
